name: Build ESPHome Firmware

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create ESPHome config
        run: |
          cat << 'EOF' > config.yaml
          esphome:
            name: xiaozhi-radio

          esp32:
            board: esp32-c3-devkitm-1
            framework:
              type: esp-idf

          wifi:
            ssid: "ИМЯ_ВАШЕГО_WIFI"
            password: "ПАРОЛЬ_ОТ_WIFI"

          web_server:
            port: 80
            version: 3

          logger:
          api:

          i2c:
            sda: GPIO10
            scl: GPIO08

          audio_dac:
            - platform: es8311
              address: 0x18

          i2s_audio:
            id: i2s_bus
            i2s_lrclk_pin: GPIO03
            i2s_bclk_pin: GPIO02

          speaker:
            - platform: i2s_audio
              id: xiaozhi_hardware_speaker
              i2s_dout_pin: GPIO01
              dac_type: external

          media_player:
            - platform: speaker
              id: audio_player
              name: "Xiaozhi Internet Radio"
              media_pipeline:
                speaker: xiaozhi_hardware_speaker
              announcement_pipeline:
                speaker: xiaozhi_hardware_speaker
          EOF

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ESPHome
        run: pip install esphome

      - name: Compile Firmware
        run: esphome compile config.yaml

      # НОВОЕ: Отправка файла на файлообменник и вывод ссылки прямо в лог текстом!
      - name: Print Direct Download Link
        run: |
          echo "=========================================================="
          echo "ВАША ССЫЛКА НА СКАЧИВАНИЕ ПРОШИВКИ:"
          curl -X POST --data-binary @.esphome/build/xiaozhi-radio/firmware-factory.bin https://bashupload.com
          echo "=========================================================="
